name: CI

on:
  push:
  pull_request:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files
